[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_escrow = "DaZi9KM615w3XuSL6PMRQ4inmRCrmkx7xrYAkRVfGjqB"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
