[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
test_hello_world = "2vsE5aDsFLfCFzG6EWvj32dzQem2p7qPzQnAfLX8TMgR"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
