[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault = "GhDfuDfxeaDFrZmVGqApr43V2sSr8Unydt5tGi2zNUn3"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
