[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_dice_game = "8hjbFtnfY87ZzpEpx26u5tx4KjxkrqiWGUEcWFbDNn7h"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
